apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
  name: drone-ingress
  namespace: drone-system
spec:
  rules:
  - host: drone.devheaven.nl
    http:
      paths:
      - backend:
          serviceName: drone-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - drone.devheaven.nl
    secretName: drone-cert